version: '3.3'

services:
  jenkins:
    #build:
    #  context: ./master
    image: alpeza/jenkins:1.0.0
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home_summit:/var/jenkins_home
      - ./casc_configs:/var/jenkins_conf
      - /home/alpeza/HomeCI/repo:/home
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - github
      - adminpw
      - dockerhub
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
      - REPO_PATH=/home
    networks:
      - core_npm_hcinet
secrets:
  #Be careful with newlines in your secrets, make sure to remove them before running docker-compose up.
  github:
    file: secrets/github
  adminpw:
    file: secrets/adminpw
  dockerhub:
    file: secrets/dockerhub
volumes:
  jenkins_home_summit:


networks:
  core_npm_hcinet:
    external: true
